services:
    asdoria_product_document.twig.document_extension:
        class: Asdoria\SyliusProductDocumentPlugin\Twig\DocumentExtension
        arguments:
            $webPathHelper: '@asdoria_product_document.helper.web_path_helper'
        tags:
            - { name: 'twig.extension' }

    asdoria_product_document.helper.web_path_helper:
        class: Asdoria\SyliusProductDocumentPlugin\Helper\WebPathHelper
        arguments:
            $fileSystem: '@asdoria.media.document_uploader.file_system'
            $pathResolver: '@liip_imagine.cache.resolver.default'
