services:
    #Document
    asdoria_product_document.media.document_uploader:
        public: true
        class: '%asdoria_product_document.media.document_uploader%'
        arguments: [ '@asdoria_product_document.media.document_adapter.file_system' ]
