asdoria_shop_product_document_download_file:
    path: /media/document/resolve/{path}
    defaults:
        _controller: asdoria.controller.product_document:downloadAction
        _sylius:
            repository:
                method: findOneByPath
                arguments:
                    - $path
    options:
        expose: true
    methods:
        - GET
    requirements:
        path: .+
