Asdoria\SyliusProductDocumentPlugin\Entity\DocumentType:
    attributes:
        id:
            groups:
                - admin:product:read
                - shop:product:read
                - admin:product_document:read
                - admin:product_document:create
                - admin:document_type:read
                - admin:document_type:create
        code:
            groups:
                - admin:product:read
                - shop:product:read
                - admin:product:create
                - admin:product:update
                - admin:product_document:read
                - admin:product_document:create
                - admin:document_type:read
                - admin:document_type:create
        name:
            groups:
                - admin:product:read
                - shop:product:read
                - admin:product:create
                - admin:product:update
                - admin:product_document:read
                - admin:product_document:create
                - admin:document_type:read
                - admin:document_type:create
